[[minimap2]]
arch = "aarch64"
git-tree-sha1 = "db08ae10088f0990de929022f0296f7b6409d2ea"
os = "macos"

    [[minimap2.download]]
    sha256 = "d95c7e34ae0c1ec36b1f2debc823081907b91429ed50f34226660e277196b8df"
    url = "https://github.com/JuliaBinaryWrappers/minimap2_jll.jl/releases/download/minimap2-v2.28.0+0/minimap2.v2.28.0.aarch64-apple-darwin.tar.gz"
[[minimap2]]
arch = "aarch64"
git-tree-sha1 = "acc7ece9ff162dd5404a86fc25035a8d82d7cc05"
libc = "glibc"
os = "linux"

    [[minimap2.download]]
    sha256 = "2a970480a63e2c8572d5d9ac8c70c2361a258b5bdc019da70e3dd71b9fbcee6c"
    url = "https://github.com/JuliaBinaryWrappers/minimap2_jll.jl/releases/download/minimap2-v2.28.0+0/minimap2.v2.28.0.aarch64-linux-gnu.tar.gz"
[[minimap2]]
arch = "aarch64"
git-tree-sha1 = "f98748f79959d890a0cd64f5d9def41820168798"
libc = "musl"
os = "linux"

    [[minimap2.download]]
    sha256 = "1507630db7cdb973a8d3ac59919b9de21be56d5bb6aa2f691fdce8981447d721"
    url = "https://github.com/JuliaBinaryWrappers/minimap2_jll.jl/releases/download/minimap2-v2.28.0+0/minimap2.v2.28.0.aarch64-linux-musl.tar.gz"
[[minimap2]]
arch = "x86_64"
git-tree-sha1 = "3dddf633bf8a1ec20d0c35e6cf47b9b087c25ed1"
os = "macos"

    [[minimap2.download]]
    sha256 = "3872d2adfaec5f1b8757795592adaa2f904673e27d2d68948055fc5f7acc2d2b"
    url = "https://github.com/JuliaBinaryWrappers/minimap2_jll.jl/releases/download/minimap2-v2.28.0+0/minimap2.v2.28.0.x86_64-apple-darwin.tar.gz"
[[minimap2]]
arch = "x86_64"
git-tree-sha1 = "f9de9a69f18d9d89e723fabde91625ea1df21561"
libc = "glibc"
os = "linux"

    [[minimap2.download]]
    sha256 = "c09f7b64a22231307014eb2871e92a6c6677c1b22a996f4c0d668bcef37c308f"
    url = "https://github.com/JuliaBinaryWrappers/minimap2_jll.jl/releases/download/minimap2-v2.28.0+0/minimap2.v2.28.0.x86_64-linux-gnu.tar.gz"
[[minimap2]]
arch = "x86_64"
git-tree-sha1 = "3be833196cf1b425aa01dbd83a83e34682e75010"
libc = "musl"
os = "linux"

    [[minimap2.download]]
    sha256 = "e5245add800078691e6c2abf2253416e23b856c92e8bf1fc82308cd3b614fae3"
    url = "https://github.com/JuliaBinaryWrappers/minimap2_jll.jl/releases/download/minimap2-v2.28.0+0/minimap2.v2.28.0.x86_64-linux-musl.tar.gz"
[[minimap2]]
arch = "x86_64"
git-tree-sha1 = "14aa72e34f979215b84058a82480f779bf1016b7"
os = "freebsd"

    [[minimap2.download]]
    sha256 = "675d543fb89c4dce246b55f5fb551efa40df31d4d2d54c7c256b33d1289cfbbb"
    url = "https://github.com/JuliaBinaryWrappers/minimap2_jll.jl/releases/download/minimap2-v2.28.0+0/minimap2.v2.28.0.x86_64-unknown-freebsd.tar.gz"
[[minimap2]]
arch = "x86_64"
git-tree-sha1 = "db63bb8a4dc233e28c8b491abdd9ba382d584aea"
os = "windows"

    [[minimap2.download]]
    sha256 = "3b438c2b946904fb3ab0324e224ef2b1c4be7a288f20cf2045793a363bbb92bb"
    url = "https://github.com/JuliaBinaryWrappers/minimap2_jll.jl/releases/download/minimap2-v2.28.0+0/minimap2.v2.28.0.x86_64-w64-mingw32.tar.gz"
