# Autogenerated wrapper script for minimap2_jll for x86_64-linux-musl
export minimap2

using Zlib_jll
JLLWrappers.@generate_wrapper_header("minimap2")
JLLWrappers.@declare_executable_product(minimap2)
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll)
    JLLWrappers.@init_executable_product(
        minimap2,
        "bin/minimap2",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
